import Footer from "./components/Footer/index";
import Navbar from "./components/Navbar/index";
import "./globals.css";

export const metadata = {
  title: "highkey consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className="flex flex-col justify-between min-h-screen">
        <script async src="//www.instagram.com/embed.js"></script>

        <Navbar />
        <div className="lg:mt-28">{children}</div>
        <Footer  />
      </body>
    </html>
  );
}
